#!/bin/sh
# ~/.vnc/xstartup on the server

export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &
gnome-session &
gnome-panel &
gnome-settings-daemon &
metacity &
nautilus &
gnome-terminal &
autocutsel &  # For clipboard to work between host and VM
/opt/jetbrains/idea/bin/idea.sh &  # My IDE of choice
xfce4-terminal &  # Open a terminal window at startup
gpg-agent --daemon  # Run the GPG agent in the background

